from fuses import FUSES
from service_points import SERVICEPOINT
from transformers import TRANSFORMER
from lights import STREETLIGHT
from simple_points import (SWITCH, ELECTRIC_STATION, VOLTAGE_REGULATOR,
                           DYNAMIC_PROTECTION_DEVICE, PF_CORRECTING_EQUIPMENT)
POINTS = {**FUSES, **SERVICEPOINT, **TRANSFORMER, **STREETLIGHT, **SWITCH, **VOLTAGE_REGULATOR,
          **ELECTRIC_STATION, **DYNAMIC_PROTECTION_DEVICE, **PF_CORRECTING_EQUIPMENT}